# Extra Variables:
#  ${FUNCTION_NAME}: lambda function name
#  ${FUNCTION_PATH}: namespace given to function via path in functions folder
#  ${FUNCTION_SRC}: path to function source code relative to build folder
#  All available in config/resources.yml

${FUNCTION_NAME}:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: ${FUNCTION_SRC}
    Handler: function.handler

    Environment:
      Variables:
        FOO: ${FOO}
        BAR: ${BAR}

    Events:

      Touch${FUNCTION_NAME}:
        Type: Api
        Properties:
          Path: /${FUNCTION_PATH}
          Method: options
      TouchExtra${FUN}:
        Type: Api
        Properties:
          Path: /${FUNCTION_PATH}/{extra+}
          Method: options

      Get${FUNCTION_NAME}:
        Type: Api
        Properties:
          Path: /${FUNCTION_PATH}
          Method: get
      GetExtra${FUN}:
        Type: Api
        Properties:
          Path: /${FUNCTION_PATH}/{extra+}
          Method: get

      Post${FUNCTION_NAME}:
        Type: Api
        Properties:
          Path: /${FUNCTION_PATH}
          Method: post
      PostExtra${FUN}:
        Type: Api
        Properties:
          Path: /${FUNCTION_PATH}/{extra+}
          Method: post
