# Variables:
#  ${FUN}: (pathlike) location of source code in functions folder
#  ${FUN_NAME}: lambda function's name (${APP_NAME} + titleized ${FUN})
#  ${PATH}: the path to the function within the functions folder
#  ${CODE}: the path to the function code within the build folder
#  All available in master config/template.yml

${FUN_NAME}:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: ${CODE}
    Handler: function.handler
    Events:

      Touch${FUN_NAME}:
        Type: Api
        Properties:
          Path: /${PATH}
          Method: options
      TouchExtra${FUN_NAME}:
        Type: Api
        Properties:
          Path: /${PATH}/{extra+}
          Method: options

      Get${FUN_NAME}:
        Type: Api
        Properties:
          Path: /${PATH}
          Method: get
      GetExtra${FUN_NAME}:
        Type: Api
        Properties:
          Path: /${PATH}/{extra+}
          Method: get

      Post${FUN_NAME}:
        Type: Api
        Properties:
          Path: /${PATH}
          Method: post
      PostExtra${FUN_NAME}:
        Type: Api
        Properties:
          Path: /${PATH}/{extra+}
          Method: post
