# Extra Variables:
#  ${BUILD_HASH}: unique SHA for this build
#  ${BUILD_AUTHOR}: AWS username of person who ran this build

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Starter Lambda Project

Globals:
  Function:
    Runtime: python3.7
    AutoPublishAlias: Live
    Tags:
      Type: Application
      App: ${APP}
      Env: ${ENV}
      Author: ${BUILD_AUTHOR}
      Build: ${BUILD_HASH}

# Resources: will be appended to the end of this file
